const Images = {
    partyLogo: require('../images/partyLogoEdited.png').default,
    image1: require('../images/MainCarousel/img1.jpg').default,
    image2: require('../images/MainCarousel/img3.jpg').default,
    image3: require('../images/MainCarousel/img7.jpeg').default,
    image4: require('../images/MainCarousel/img11.jpg').default,
    leader: require('../images/leader.jpg').default,
    highlight1: require('../images/MainHighlights/highlight1.jpg').default,
    highlight2: require('../images/MainHighlights/highlight2.jpg').default,
    highlight3: require('../images/MainHighlights/highlight3.jpg').default,
    highlight4: require('../images/MainHighlights/highlight4.jpg').default,
    highlight5: require('../images/MainHighlights/highlight5.jpg').default,
    map: require('../images/map.png').default,
    topEvent: require('../images/LatestEvent/events.png').default,
    man: require('../images/LatestEvent/man.jpg').default,
    news: require('../images/LatestEvent/news.jpg').default, 
    aboutBack: require('../images/About/aboutBack.png').default,
    puri: require('../images/About/puri.png').default,
    topImage: require('../images/LatestEvent/topImage.jpg').default,
    vijaynderSingh: require('../images/Member/vijaynderSingh.jpg').default,
    dineshKumarGupta: require('../images/Member/dineshKumarGupta.jpg').default,
    rajniPareshar: require('../images/Member/rajniPareshar.jpg').default,
    vinodUpadhyay: require('../images/Member/vinodUpadhyay.jpg').default,
    abhishekBhatt: require('../images/Member/abhishekBhatt.jpg').default,
    vishalKrishna: require('../images/Member/vishalKrishna.jpg').default,
    ashwiniKumarSharma: require('../images/Member/ashwiniKumarSharma.jpg').default,
    deepakSharma: require('../images/Member/deepakSharma.jpg').default,
    hireshSingh: require('../images/Member/hireshSingh.jpg').default,
    varunShaurya: require('../images/Member/varunShaurya.jpg').default,
    joinBack: require('../images/joinBack.jpg').default,
    adi: require('../images/About/adi.png').default,
    aboutNjp: require('../images/mapBack.jpg').default,
}

export default Images;